load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("@aspect_rules_js//js:defs.bzl", "js_library")
load("//javascript:defs.bzl", "mocha_test")

SMALL_TESTS = [
    "io/io_test.js",
    "io/zip_test.js",
    "lib/by_test.js",
    "lib/credentials_test.js",
    "lib/error_test.js",
    "lib/http_test.js",
    "lib/input_test.js",
    "lib/logging_test.js",
    "lib/promise_test.js",
    "lib/until_test.js",
    "lib/virtualauthenticatoroptions_test.js",
    "lib/webdriver_test.js",
    "net/index_test.js",
    "net/portprober_test.js",
]

js_library(
    name = "small-test-srcs",
    srcs = SMALL_TESTS,
)

copy_to_bin(
    name = "test-data",
    srcs = glob(
        ["**"],
        exclude = ["**/*_test.js"],
    ),
)

mocha_test(
    name = "small-tests",
    size = "small",
    args = ["./**/*test.js"],
    chdir = package_name(),
    data = [
        ":small-test-srcs",
        ":test-data",
        "//:node_modules/selenium-webdriver",
        "//common/extensions:js-lib",
        "//common/src/web:js-lib",
        "//javascript/node/selenium-webdriver:node_modules/@bazel/runfiles",
        "//javascript/node/selenium-webdriver:node_modules/mocha",
        "//javascript/node/selenium-webdriver:node_modules/mocha-junit-reporter",
        "//javascript/node/selenium-webdriver:node_modules/sinon",
    ],
)

LARGE_TESTS = glob(
    ["**/*_test.js"],
    exclude = SMALL_TESTS,
)

js_library(
    name = "large-test-srcs",
    srcs = LARGE_TESTS,
)

#mocha_test(
#    name = "browser-test",
#    size = "large",
#    args = [
#        "--retries",
#        "1",
#        "element_finding_test.js",
#    ],
#    chdir = package_name(),
#    data = [
#        "element_finding_test.js",
#    ],
#)

#[
#    [
#        mocha_test(
#            name = "%s-%s" % (
#                test.replace("/", "-").replace("_", "-"),
#                browser,
#            ),
#            size = "large",
#            args = [
#                "--retries",
#                "1",
#                test,
#            ],
#            chdir = package_name(),
#            data = [
#                "test-data",
#                ":large-test-srcs",
#                ":node_modules/@bazel/runfiles",
#                ":node_modules/express",
#                ":node_modules/jszip",
#                ":node_modules/multer",
#                ":node_modules/serve-index",
#                ":node_modules/sinon",
#                ":node_modules/tmp",
#                ":node_modules/ws",
#                "//:node_modules/selenium-webdriver",
#                "//common/extensions:js-lib",
#                "//common/src/web:js-lib",
#                "//javascript/node/selenium-webdriver/lib/atoms:find-elements",
#                "//javascript/node/selenium-webdriver/lib/atoms:get_attribute",
#                "//javascript/node/selenium-webdriver/lib/atoms:is_displayed",
#                "//javascript/node/selenium-webdriver/lib/atoms:mutation-listener",
#            ],
#            env = {
#                "SELENIUM_BROWSER": browser,
#            },
#            tags = [
#                browser,
#                "browser-test",
#                "no-sandbox",
#                "requires-network",
#                "skip-remote",
#            ],
#        ),
#    ]
#    for test in LARGE_TESTS
#    for browser in [
#        "chrome",
#        "firefox",
#    ]
#]
