load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "log",
    srcs = [
        "BaseLogEntry.java",
        "ConsoleLogEntry.java",
        "FilterBy.java",
        "GenericLogEntry.java",
        "JavascriptLogEntry.java",
        "Log.java",
        "LogEntry.java",
        "LogLevel.java",
        "StackFrame.java",
        "StackTrace.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/bidi/script"],
    deps = [
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/bidi/script",
        "//java/src/org/openqa/selenium/json",
    ],
)
