load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "bidi",
    srcs = [
        "BiDi.java",
        "BiDiException.java",
        "BiDiProvider.java",
        "BiDiSessionStatus.java",
        "Command.java",
        "Connection.java",
        "ConverterFunctions.java",
        "Event.java",
        "HasBiDi.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/json",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
