java_library(
    name = "grid",
    srcs = glob(["*.java"]),
    deps = [
        "//java/client/src/org/openqa/selenium/remote:remote",
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/server/src/org/openqa/selenium/events/zeromq:zeromq",
        "//java/server/src/org/openqa/selenium/grid/distributor:distributor",
        "//java/server/src/org/openqa/selenium/grid/distributor/local:local",
        "//java/server/src/org/openqa/selenium/grid/distributor/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/node/local:local",
        "//java/server/src/org/openqa/selenium/grid/node/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/router:router",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/local:local",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/web:web",
    ],
    visibility = [
    ],
)

java_binary(
    name = "topology",
    main_class = "org.openqa.selenium.grid.GridTopology",
    deps = [
        ":grid",
    ],
)
