load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "browsingcontext",
    srcs = [
        "BoxClipRectangle.java",
        "BrowsingContext.java",
        "BrowsingContextInfo.java",
        "CaptureScreenshotParameters.java",
        "ClipRectangle.java",
        "CreateContextParameters.java",
        "ElementClipRectangle.java",
        "HistoryUpdated.java",
        "LocateNodeParameters.java",
        "Locator.java",
        "NavigationInfo.java",
        "NavigationResult.java",
        "ReadinessState.java",
        "UserPromptClosed.java",
        "UserPromptOpened.java",
        "UserPromptType.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/bidi/script"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/bidi/script",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/print",
    ],
)
