load("@rules_jvm_external//:defs.bzl", "artifact")
load("//common:defs.bzl", "copy_file")
load("//java:defs.bzl", "java_export")
load("//java:version.bzl", "SE_VERSION")

java_export(
    name = "manager",
    srcs = glob(["*.java"]),
    maven_coordinates = "org.seleniumhq.selenium:selenium-manager:%s" % SE_VERSION,
    pom_template = "//java/src/org/openqa/selenium:template-pom",
    resources = [
        ":manager-linux-x86_64",
        ":manager-macos-arm64",
        ":manager-macos-x86_64",
        ":manager-windows-x86_64",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        artifact("com.google.guava:guava"),
    ],
)

copy_file(
    name = "manager-linux-x86_64",
    src = "//rust:selenium-manager-linux-x86_64",
    out = "linux/x86_64/selenium-manager",
)

copy_file(
    name = "manager-windows-x86_64",
    src = "//common/manager:windows/selenium-manager.exe",
    out = "windows/x86_64/selenium-manager.exe",
)

copy_file(
    name = "manager-macos-arm64",
    src = "//rust:selenium-manager-macos-arm64",
    out = "macos/arm64/selenium-manager",
)

copy_file(
    name = "manager-macos-x86_64",
    src = "//rust:selenium-manager-macos-x86_64",
    out = "macos/x86_64/selenium-manager",
)
