load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "opentelemetry",
    srcs = [
        "OpenTelemetryAttributeMap.java",
        "OpenTelemetryContext.java",
        "OpenTelemetryPropagator.java",
        "OpenTelemetrySpan.java",
        "OpenTelemetryTracer.java",
        "SeleniumSpanExporter.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/remote/tracing",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:io_opentelemetry_opentelemetry_context",
        "@maven//:io_opentelemetry_opentelemetry_sdk_common",
        "@maven//:io_opentelemetry_opentelemetry_sdk_trace",
    ],
    deps = [
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote/tracing",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:io_opentelemetry_opentelemetry_context",
        "@maven//:io_opentelemetry_opentelemetry_sdk",
        "@maven//:io_opentelemetry_opentelemetry_sdk_common",
        "@maven//:io_opentelemetry_opentelemetry_sdk_extension_autoconfigure",
        "@maven//:io_opentelemetry_opentelemetry_sdk_trace",
    ],
)
