load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "internal",
    srcs = [
        "ImageSummary.java",
        "Reference.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/docker"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/docker",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "@maven//:com_google_guava_guava",
    ],
)
