load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "json",
    srcs = [
        "BooleanCoercer.java",
        "CollectionCoercer.java",
        "EnumCoercer.java",
        "Input.java",
        "InstanceCoercer.java",
        "InstantCoercer.java",
        "Json.java",
        "JsonException.java",
        "JsonInput.java",
        "JsonInputIterator.java",
        "JsonOutput.java",
        "JsonType.java",
        "JsonTypeCoercer.java",
        "MapCoercer.java",
        "NumberCoercer.java",
        "ObjectCoercer.java",
        "PropertySetting.java",
        "SimplePropertyDescriptor.java",
        "StaticInitializerCoercer.java",
        "StringCoercer.java",
        "TypeCoercer.java",
        "TypeToken.java",
        "Types.java",
        "UriCoercer.java",
        "UrlCoercer.java",
        "UuidCoercer.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/logging",
    ],
)
