load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_library(
    name = "grid",
    srcs = [
        "ActualMain.java",
        "Bootstrap.java",
        "Main.java",
        "TemplateGridCommand.java",
        "TemplateGridServerCommand.java",
        "package-info.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium/cli",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/netty/server",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_guava_guava",
    ],
)

java_binary(
    name = "Bootstrap",
    main_class = "org.openqa.selenium.grid.Bootstrap",
    visibility = ["//visibility:public"],
    runtime_deps = [":grid"],
)

java_binary(
    name = "Main",
    main_class = "org.openqa.selenium.grid.Main",
    visibility = ["//visibility:public"],
    runtime_deps = [":grid"],
)
