load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "decorators",
    srcs = [
        "Decorated.java",
        "DefaultDecorated.java",
        "WebDriverDecorator.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/virtualauthenticator",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/virtualauthenticator",
        "@maven//:net_bytebuddy_byte_buddy",
    ],
)
