load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_library(
    name = "devtools-prototypes",
    srcs = [
        "Command.java",
        "ConverterFunctions.java",
        "DevToolsException.java",
        "Event.java",
    ],
    visibility = [
        "//java/src/org/openqa/selenium/devtools:__subpackages__",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/json",
    ],
)

java_library(
    name = "devtools",
    srcs = [
        "CdpClientGenerator.java",
        "CdpEndpointFinder.java",
        "CdpInfo.java",
        "CdpVersionFinder.java",
        "Command.java",
        "Connection.java",
        "ConverterFunctions.java",
        "DevTools.java",
        "DevToolsException.java",
        "DevToolsProvider.java",
        "Event.java",
        "HasDevTools.java",
        "Message.java",
        "NetworkInterceptor.java",
        "Reply.java",
        "RequestFailedException.java",
        "SeleniumCdpConnection.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/devtools/idealized",
        "//java/src/org/openqa/selenium/devtools/idealized/target/model",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_github_javaparser_javaparser_core",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/devtools/idealized",
        "//java/src/org/openqa/selenium/devtools/idealized/target/model",
        "//java/src/org/openqa/selenium/devtools/noop",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_github_javaparser_javaparser_core",
        "@maven//:com_google_auto_service_auto_service_annotations",
        "@maven//:com_google_guava_guava",
    ],
)

java_binary(
    name = "CdpClientGenerator",
    main_class = "org.openqa.selenium.devtools.CdpClientGenerator",
    visibility = ["//visibility:public"],
    runtime_deps = [":devtools"],
)

alias(
    name = "cdp-client-generator",
    actual = ":CdpClientGenerator",
    visibility = [
        "//java/src/org/openqa/selenium/devtools:__subpackages__",
    ],
)
