load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "selector",
    srcs = [
        "DefaultSlotSelector.java",
        "GreedySlotSelector.java",
        "SlotSelector.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/grid/data"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "@maven//:com_google_guava_guava",
    ],
)
