load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "config",
    srcs = [
        "NewSessionQueueFlags.java",
        "NewSessionQueueOptions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/sessionqueue",
    ],
    deps = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/jmx",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/grid/sessionqueue",
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
