load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "idealized",
    srcs = [
        "Domains.java",
        "Events.java",
        "Javascript.java",
        "Network.java",
        "OpaqueKey.java",
        "ScriptId.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/devtools/events",
        "//java/src/org/openqa/selenium/devtools/idealized/log",
        "//java/src/org/openqa/selenium/devtools/idealized/target",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/devtools",
        "//java/src/org/openqa/selenium/devtools/events",
        "//java/src/org/openqa/selenium/devtools/idealized/log",
        "//java/src/org/openqa/selenium/devtools/idealized/target",
        "//java/src/org/openqa/selenium/devtools/idealized/target/model",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/remote/http",
    ],
)
