load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "logging",
    srcs = [
        "CompositeLocalLogs.java",
        "EventType.java",
        "HandlerBasedLocalLogs.java",
        "HasLogEvents.java",
        "LocalLogs.java",
        "LogCombiner.java",
        "LogEntries.java",
        "LogEntry.java",
        "LogLevelMapping.java",
        "LogType.java",
        "LoggingHandler.java",
        "LoggingPreferences.java",
        "Logs.java",
        "NeedsLocalLogs.java",
        "SessionLogHandler.java",
        "SessionLogs.java",
        "StoringLocalLogs.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "@maven//:org_jspecify_jspecify",
    ],
)
