load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "remote",
    srcs = [
        "AbstractDriverOptions.java",
        "AddHasAuthentication.java",
        "AddHasLogEvents.java",
        "AddWebDriverSpecHeaders.java",
        "AdditionalHttpCommands.java",
        "Augmentable.java",
        "Augmenter.java",
        "AugmenterProvider.java",
        "Browser.java",
        "CapabilityType.java",
        "Command.java",
        "CommandCodec.java",
        "CommandExecutor.java",
        "CommandInfo.java",
        "CommandPayload.java",
        "DesiredCapabilities.java",
        "Dialect.java",
        "DomMutation.java",
        "DriverCommand.java",
        "ElementLocation.java",
        "ErrorCodec.java",
        "ErrorCodes.java",
        "ErrorFilter.java",
        "ErrorHandler.java",
        "ExecuteMethod.java",
        "FedCmDialogImpl.java",
        "FileDetector.java",
        "HandshakeResponse.java",
        "HttpCommandExecutor.java",
        "HttpSessionId.java",
        "InitialHandshakeResponse.java",
        "JsonToWebElementConverter.java",
        "LocalFileDetector.java",
        "Network.java",
        "NewSessionPayload.java",
        "NoSuchDriverException.java",
        "ProtocolHandshake.java",
        "RemoteExecuteMethod.java",
        "RemoteLogs.java",
        "RemoteNetwork.java",
        "RemoteScript.java",
        "RemoteTags.java",
        "RemoteWebDriver.java",
        "RemoteWebDriverBuilder.java",
        "RemoteWebElement.java",
        "Response.java",
        "ResponseCodec.java",
        "ScreenshotException.java",
        "Script.java",
        "SessionId.java",
        "ShadowRoot.java",
        "TracedCommandExecutor.java",
        "UnreachableBrowserException.java",
        "UselessFileDetector.java",
        "W3CHandshakeResponse.java",
        "WebElementToJsonConverter.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi/script",
        "//java/src/org/openqa/selenium/federatedcredentialmanagement",
        "//java/src/org/openqa/selenium/interactions",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/virtualauthenticator",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/bidi/log",
        "//java/src/org/openqa/selenium/bidi/module",
        "//java/src/org/openqa/selenium/bidi/network",
        "//java/src/org/openqa/selenium/bidi/script",
        "//java/src/org/openqa/selenium/devtools",
        "//java/src/org/openqa/selenium/federatedcredentialmanagement",
        "//java/src/org/openqa/selenium/interactions",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/io",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/print",
        "//java/src/org/openqa/selenium/remote/codec/w3c",
        "//java/src/org/openqa/selenium/remote/html5",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/service",
        "//java/src/org/openqa/selenium/remote/tracing",
        "//java/src/org/openqa/selenium/remote/tracing/opentelemetry",
        "//java/src/org/openqa/selenium/support/decorators",
        "//java/src/org/openqa/selenium/virtualauthenticator",
        "@maven//:net_bytebuddy_byte_buddy",
        "@maven//:org_jspecify_jspecify",
    ],
)
