load("@rules_java//java:defs.bzl", "java_library")
load("//java:defs.bzl", "java_export")

java_export(
    #    glob([
    #        "*.java",
    #        "federatedcredentialmanagement/*.java",
    #        "html5/*.java",
    #        "internal/*.java",
    #        "interactions/**/*.java",
    #        "logging/**/*.java",
    #        "net/*.java",
    #        "virtualauthenticator/*.java",
    #        "print/*.java",
    #    ]),
    srcs = [
        "AcceptedW3CCapabilityKeys.java",
        "Alert.java",
        "Architecture.java",
        "Beta.java",
        "BuildInfo.java",
        "By.java",
        "Capabilities.java",
        "Cookie.java",
        "Credentials.java",
        "DetachedShadowRootException.java",
        "DeviceRotation.java",
        "Dimension.java",
        "ElementClickInterceptedException.java",
        "ElementNotInteractableException.java",
        "HasAuthentication.java",
        "HasCapabilities.java",
        "HasDownloads.java",
        "HealthCheckFailedException.java",
        "ImmutableCapabilities.java",
        "InsecureCertificateException.java",
        "InvalidArgumentException.java",
        "InvalidCookieDomainException.java",
        "InvalidElementStateException.java",
        "InvalidSelectorException.java",
        "JavascriptException.java",
        "JavascriptExecutor.java",
        "Keys.java",
        "MutableCapabilities.java",
        "NoAlertPresentException.java",
        "NoSuchCookieException.java",
        "NoSuchElementException.java",
        "NoSuchFrameException.java",
        "NoSuchSessionException.java",
        "NoSuchShadowRootException.java",
        "NoSuchWindowException.java",
        "NotFoundException.java",
        "OutputType.java",
        "PageLoadStrategy.java",
        "Pdf.java",
        "PersistentCapabilities.java",
        "Platform.java",
        "Point.java",
        "PrintsPage.java",
        "Proxy.java",
        "Rectangle.java",
        "RetrySessionRequestException.java",
        "ScreenOrientation.java",
        "ScriptKey.java",
        "ScriptTimeoutException.java",
        "SearchContext.java",
        "SessionNotCreatedException.java",
        "SharedCapabilitiesMethods.java",
        "StaleElementReferenceException.java",
        "TakesScreenshot.java",
        "TimeoutException.java",
        "UnableToSetCookieException.java",
        "UnexpectedAlertBehaviour.java",
        "UnhandledAlertException.java",
        "UnpinnedScriptKey.java",
        "UnsupportedCommandException.java",
        "UsernameAndPassword.java",
        "WebDriver.java",
        "WebDriverException.java",
        "WebDriverInfo.java",
        "WebElement.java",
        "WindowType.java",
        "WrapsDriver.java",
        "WrapsElement.java",
    ],
    hides = [
        "org.openqa.selenium.interactions.internal",
    ],
    maven_coordinates = "org.seleniumhq.selenium:selenium-api:%s" % SE_VERSION,
    opens_to = [
        "org.seleniumhq.selenium.json",
    ],
    pom_template = ":template-pom",
    tags = [
        "release-artifact",
    ],
    visibility = ["//visibility:public"],
)

java_library(
    name = "selenium",
    srcs = [
        "AcceptedW3CCapabilityKeys.java",
        "Alert.java",
        "Architecture.java",
        "Beta.java",
        "BuildInfo.java",
        "By.java",
        "Capabilities.java",
        "Cookie.java",
        "Credentials.java",
        "DetachedShadowRootException.java",
        "DeviceRotation.java",
        "Dimension.java",
        "ElementClickInterceptedException.java",
        "ElementNotInteractableException.java",
        "HasAuthentication.java",
        "HasCapabilities.java",
        "HasDownloads.java",
        "HealthCheckFailedException.java",
        "ImmutableCapabilities.java",
        "InsecureCertificateException.java",
        "InvalidArgumentException.java",
        "InvalidCookieDomainException.java",
        "InvalidElementStateException.java",
        "InvalidSelectorException.java",
        "JavascriptException.java",
        "JavascriptExecutor.java",
        "Keys.java",
        "MutableCapabilities.java",
        "NoAlertPresentException.java",
        "NoSuchCookieException.java",
        "NoSuchElementException.java",
        "NoSuchFrameException.java",
        "NoSuchSessionException.java",
        "NoSuchShadowRootException.java",
        "NoSuchWindowException.java",
        "NotFoundException.java",
        "OutputType.java",
        "PageLoadStrategy.java",
        "Pdf.java",
        "PersistentCapabilities.java",
        "Platform.java",
        "Point.java",
        "PrintsPage.java",
        "Proxy.java",
        "Rectangle.java",
        "RetrySessionRequestException.java",
        "ScreenOrientation.java",
        "ScriptKey.java",
        "ScriptTimeoutException.java",
        "SearchContext.java",
        "SessionNotCreatedException.java",
        "SharedCapabilitiesMethods.java",
        "StaleElementReferenceException.java",
        "TakesScreenshot.java",
        "TimeoutException.java",
        "UnableToSetCookieException.java",
        "UnexpectedAlertBehaviour.java",
        "UnhandledAlertException.java",
        "UnpinnedScriptKey.java",
        "UnsupportedCommandException.java",
        "UsernameAndPassword.java",
        "WebDriver.java",
        "WebDriverException.java",
        "WebDriverInfo.java",
        "WebElement.java",
        "WindowType.java",
        "WrapsDriver.java",
        "WrapsElement.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/logging"],
    deps = [
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/logging",
        "//java/src/org/openqa/selenium/net",
        "//java/src/org/openqa/selenium/print",
        "@maven//:org_jspecify_jspecify",
    ],
)
