load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "data",
    srcs = [
        "Availability.java",
        "CapabilityCount.java",
        "CreateSessionRequest.java",
        "CreateSessionResponse.java",
        "DefaultSlotMatcher.java",
        "DistributorStatus.java",
        "NewSessionErrorResponse.java",
        "NewSessionResponse.java",
        "NewSessionResponseEvent.java",
        "NodeAddedEvent.java",
        "NodeDrainComplete.java",
        "NodeDrainStarted.java",
        "NodeHeartBeatEvent.java",
        "NodeId.java",
        "NodeRejectedEvent.java",
        "NodeRemovedEvent.java",
        "NodeRestartedEvent.java",
        "NodeStatus.java",
        "NodeStatusEvent.java",
        "RequestId.java",
        "SemanticVersionComparator.java",
        "Session.java",
        "SessionClosedEvent.java",
        "SessionRequest.java",
        "SessionRequestCapability.java",
        "Slot.java",
        "SlotId.java",
        "SlotMatcher.java",
        "TraceSessionRequest.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/tracing",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/tracing",
    ],
)
