load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "os",
    srcs = [
        "ExecutableFinder.java",
        "ExternalProcess.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/io",
    ],
)
