load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "drivers",
    srcs = [
        "driver.go",
        "geckodriver.go",
    ],
    importpath = "github.com/SeleniumHQ/selenium/golang/pkg/drivers",
    visibility = ["//visibility:public"],
    deps = [
        "//golang/internal/platforms",
        "@com_github_hashicorp_go_version//:go-version",
        "@com_github_sirupsen_logrus//:logrus",
    ],
)
