load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "cli",
    srcs = [
        "CliCommand.java",
        "WrappedPrintWriter.java",
        "package-info.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/grid/config"],
    deps = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/internal",
    ],
)
