load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "tracing",
    srcs = [
        "AttributeKey.java",
        "AttributeMap.java",
        "HttpTracing.java",
        "Propagator.java",
        "Span.java",
        "SpanDecorator.java",
        "SpanWrappedHttpHandler.java",
        "SpanWrappedRoutable.java",
        "Status.java",
        "Tags.java",
        "TraceContext.java",
        "TracedHttpClient.java",
        "Tracer.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/remote/http"],
    deps = [
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/remote/http",
    ],
)
