java_library(
  name = "support",
  srcs = glob(["**/*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium/remote",
    "//third_party/java/guava",
  ],
  visibility = [
    "//visibility:public",
  ],
)