load("@crates//:defs.bzl", "all_crate_deps")
load("//rust:defs.bzl", "rust_test_suite", "rustfmt_config")

_CARGO_TOML = "rust/Cargo.toml"
_DEPS = all_crate_deps(
    package_name = _CARGO_TOML,
    normal = True,
    normal_dev = True,
)
_PROC_MACRO_DEPS = all_crate_deps(
    package_name = _CARGO_TOML,
    proc_macro = True,
    proc_macro_dev = True,
)

rustfmt_config(
    name = "enable-rustfmt",
)

rust_test_suite(
    name = "integration",
    size = "small",
    srcs = glob(["**/*_tests.rs"]),
    data = [
        "//rust:selenium-manager",
    ],
    edition = "2024",
    rustc_env = {
        "CARGO_BIN_EXE_selenium-manager": "rust/selenium-manager",
    },
    shared_srcs = glob(
        ["**/*.rs"],
        exclude = ["**/*_tests.rs"],
    ),
    tags = [
        "no-sandbox",
        "requires-network",
    ],
    deps = [
        "//rust:selenium_manager",
        "@rules_rust//tools/runfiles",
    ] + _DEPS,
    proc_macro_deps = _PROC_MACRO_DEPS,
)
