java_library(
    name = "playwright",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/src/org/openqa/selenium/grid:__subpackages__",
    ],
    deps = [
        "//java/src/org/openqa/selenium:core",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/netty/server",
        "//java/src/org/openqa/selenium/remote/http",
    ],
)

java_binary(
    name = "Server",
    main_class = "org.openqa.selenium.grid.playwright.PlaywrightServer",
    runtime_deps = [
        ":playwright",
    ],
)
