java_library(
  name = "chrome",
  srcs = glob(["*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium/remote",
    "//third_party/java/gson",
    "//third_party/java/guava",
  ],
  visibility = [
    "//visibility:public",
  ],
)