java_library(
  name = "firefox",
  srcs = glob([
    "*.java",
    "internal/*.java",
  ]),
  deps = [
    "//java/client/src/org/openqa/selenium/io",
    "//java/client/src/org/openqa/selenium/net",
    "//java/client/src/org/openqa/selenium/remote",
    "//java/client/src/org/openqa/selenium/os",
    "//third_party/java/guava",
  ],
  visibility = [
    "//visibility:public",
  ],
)