java_library(
  name = "interactions",
  srcs = glob([
    "*.java",
    "internal/*.java",
  ]),
  deps = [
    "//java/client/src/org/openqa/selenium:core-api",
    "//third_party/java/guava",
  ],
  visibility = [
    "//java/client/src/org/openqa/selenium:__pkg__",
  ],
)
