load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "script",
    srcs = [
        "ArrayLocalValue.java",
        "CallFunctionParameters.java",
        "ChannelValue.java",
        "ContextTarget.java",
        "DateLocalValue.java",
        "EvaluateParameters.java",
        "EvaluateResult.java",
        "EvaluateResultExceptionValue.java",
        "EvaluateResultSuccess.java",
        "ExceptionDetails.java",
        "LocalValue.java",
        "MapLocalValue.java",
        "Message.java",
        "NodeProperties.java",
        "ObjectLocalValue.java",
        "PrimitiveProtocolValue.java",
        "PrimitiveType.java",
        "RealmInfo.java",
        "RealmTarget.java",
        "RealmType.java",
        "RegExpValue.java",
        "RemoteReference.java",
        "RemoteValue.java",
        "ResultOwnership.java",
        "SerializationOptions.java",
        "SetLocalValue.java",
        "Source.java",
        "StackFrame.java",
        "StackTrace.java",
        "Target.java",
        "WindowProxyProperties.java",
        "WindowRealmInfo.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
    ],
)
