java_library(
  name = "os",
  srcs = glob(["*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium",
    "//java/client/src/org/openqa/selenium/io",
    "//third_party/java/commons:commons-exec",
    "//third_party/java/guava",
    "//third_party/java/jna",
  ],
  visibility = [
    "//java/client/src/org/openqa/selenium:__subpackages__",
  ],
)
