load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "zeromq",
    srcs = [
        "BoundZmqEventBus.java",
        "Topic.java",
        "UnboundZmqEventBus.java",
        "ZeroMqEventBus.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/events"],
    deps = [
        "//java/src/org/openqa/selenium/concurrent",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/net",
        "@maven//:com_google_guava_guava",
        "@maven//:dev_failsafe_failsafe",
        "@maven//:org_zeromq_jeromq",
    ],
)
