load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "model",
    srcs = ["LogEntry.java"],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
    ],
)
