load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "node",
    srcs = [
        "ActiveSession.java",
        "BaseActiveSession.java",
        "CapabilityResponseEncoder.java",
        "CustomLocatorHandler.java",
        "DefaultActiveSession.java",
        "DownloadFile.java",
        "Drain.java",
        "ForwardWebDriverCommand.java",
        "GetNodeSession.java",
        "HealthCheck.java",
        "IsSessionOwner.java",
        "NewNodeSession.java",
        "Node.java",
        "ProxyNodeWebsockets.java",
        "ReleaseConnection.java",
        "SessionFactory.java",
        "StatusHandler.java",
        "StopNodeSession.java",
        "TryAcquireConnection.java",
        "UploadFile.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/io",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/devtools",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/grid/web",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/io",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/codec/w3c",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/locators",
        "//java/src/org/openqa/selenium/remote/tracing",
        "//java/src/org/openqa/selenium/status",
        "@maven//:com_google_guava_guava",
    ],
)
