java_library(
  name = "net",
  srcs = glob(["*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium",
    "//third_party/java/guava",
  ],
  visibility = [
    "//java/client/src/org/openqa:__subpackages__",
    "//java/server/src/org/openqa:__subpackages__",
  ],
)
