load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")

filegroup(
    name = "extensions",
    srcs = glob([
        "*",
        "**/*",
    ]),
    visibility = [
        "//java/test/org/openqa/selenium/chrome:__pkg__",
        "//java/test/org/openqa/selenium/edge:__pkg__",
        "//java/test/org/openqa/selenium/environment:__pkg__",
        "//java/test/org/openqa/selenium/firefox:__pkg__",
        "//javascript/node/selenium-webdriver:__subpackages__",
        "//py:__pkg__",
        "//rb/spec:__subpackages__",
    ],
)

copy_to_bin(
    name = "js-lib",
    srcs = [
        ":extensions",
    ],
    visibility = [
        "//javascript/node/selenium-webdriver:__subpackages__",
    ],
)

exports_files(
    [
        "webextensions-selenium-example.xpi",
        "webextensions-selenium-example.zip",
        "webextensions-selenium-example-unsigned.zip",
    ],
    visibility = [
        "//java/test/org/openqa/selenium/firefox:__pkg__",
        "//javascript/node/selenium-webdriver:__subpackages__",
        "//py:__pkg__",
    ],
)
