
java_test(
    name = "distributor",
    srcs = glob(["*.java"]),
    labels = [
        "small",
    ],
    deps = [
        "//java/client/src/org/openqa/selenium/remote/tracing:tracing",
        "//java/client/src/org/openqa/selenium/support:support",
        "//java/server/src/org/openqa/selenium/events/zeromq:zeromq",
        "//java/server/src/org/openqa/selenium/grid/distributor:distributor",
        "//java/server/src/org/openqa/selenium/grid/distributor/local:local",
        "//java/server/src/org/openqa/selenium/grid/distributor/remote:remote",
        "//java/server/src/org/openqa/selenium/grid/node:node",
        "//java/server/src/org/openqa/selenium/grid/node/local:local",
        "//java/server/src/org/openqa/selenium/grid/sessionmap:sessionmap",
        "//java/server/src/org/openqa/selenium/grid/sessionmap/local:local",
        "//java/server/src/org/openqa/selenium/grid/web:web",
        "//java/server/test/org/openqa/selenium/grid:grid",
        "//java/server/test/org/openqa/selenium/grid/web:utils",
        "//java/server/test/org/openqa/selenium/grid:grid",
        "//third_party/java/assertj:assertj",
        "//third_party/java/junit:junit",
    ]
)
