load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "module",
    srcs = [
        "Browser.java",
        "BrowsingContextInspector.java",
        "Input.java",
        "LogInspector.java",
        "Network.java",
        "Permission.java",
        "Script.java",
        "Storage.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/bidi/browser",
        "//java/src/org/openqa/selenium/bidi/storage",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/bidi/browser",
        "//java/src/org/openqa/selenium/bidi/browsingcontext",
        "//java/src/org/openqa/selenium/bidi/log",
        "//java/src/org/openqa/selenium/bidi/network",
        "//java/src/org/openqa/selenium/bidi/permissions",
        "//java/src/org/openqa/selenium/bidi/script",
        "//java/src/org/openqa/selenium/bidi/storage",
        "//java/src/org/openqa/selenium/interactions",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
    ],
)
