load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "network",
    srcs = [
        "AddInterceptParameters.java",
        "AuthChallenge.java",
        "BaseParameters.java",
        "BeforeRequestSent.java",
        "BytesValue.java",
        "CacheBehavior.java",
        "ContinueRequestParameters.java",
        "ContinueResponseParameters.java",
        "Cookie.java",
        "FetchError.java",
        "FetchTimingInfo.java",
        "Header.java",
        "Initiator.java",
        "InterceptPhase.java",
        "ProvideResponseParameters.java",
        "RequestData.java",
        "ResponseData.java",
        "ResponseDetails.java",
        "SetCookieHeader.java",
        "UrlPattern.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/bidi/log"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi/log",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote/http",
    ],
)
