java_library(
  name = "logging",
  srcs = glob([
    "*.java",
    "profiler/*.java",
  ]),
  deps = [
    "//java/client/src/org/openqa/selenium:beta",
    "//third_party/java/gson",
    "//third_party/java/guava",
  ],
  visibility = [
    "//java/client/src/org/openqa/selenium:__pkg__",
  ],
)
