load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "http",
    srcs = [
        "AddSeleniumUserAgent.java",
        "BinaryMessage.java",
        "ClientConfig.java",
        "CloseMessage.java",
        "ConnectionFailedException.java",
        "Contents.java",
        "DumpHttpExchangeFilter.java",
        "Filter.java",
        "HttpClient.java",
        "HttpClientName.java",
        "HttpHandler.java",
        "HttpHeader.java",
        "HttpMessage.java",
        "HttpMethod.java",
        "HttpRequest.java",
        "HttpResponse.java",
        "Message.java",
        "RemoteCall.java",
        "RetryRequest.java",
        "Routable.java",
        "Route.java",
        "TextMessage.java",
        "UrlPath.java",
        "UrlTemplate.java",
        "WebSocket.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
    ],
)
