load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_binary(
    # Yes, this name is very similar to the library. Note the dash
    # instead of an underscore
    name = "selenium-manager",
    srcs = ["src/main.rs"],
    data = [
        "//third_party/cpp/macos-sysroot",
        "//third_party/cpp/macos-sysroot:marker",
    ],
    edition = "2021",
    rustc_flags = [
        "-C",
        "opt-level=z",
        "-C",
        "lto=yes",
        "-C",
        "codegen-units=1",
        "-C",
        "panic=abort",  # Abort on panic
        #        "-C",
        #        "strip=symbols",  # Strip symbols from binary*
        "-C",
        "link-arg=-L$(location //third_party/cpp/macos-sysroot:marker)/..",
        "-C",
        "link-arg=-F$(location //third_party/cpp/macos-sysroot:marker)/..",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":selenium_manager",
    ] + all_crate_deps(normal = True),
)

rust_library(
    # The name here is used as the crate name
    name = "selenium_manager",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["main.rs"],
    ),
    edition = "2021",
    deps = all_crate_deps(normal = True),
)

platform_transition_filegroup(
    name = "selenium-manager-linux-x86_64",
    srcs = [":selenium-manager"],
    target_platform = "//common:linux_x86_64",
    visibility = ["//visibility:public"],
)

platform_transition_filegroup(
    name = "selenium-manager-macos-arm64",
    srcs = [":selenium-manager"],
    target_platform = "//common:macos_arm64",
    visibility = ["//visibility:public"],
)

platform_transition_filegroup(
    name = "selenium-manager-macos-x86_64",
    srcs = [":selenium-manager"],
    target_platform = "//common:macos_x86_64",
    visibility = ["//visibility:public"],
)

platform_transition_filegroup(
    name = "selenium-manager-windows-x86_64",
    srcs = [":selenium-manager"],
    target_platform = "//common:windows_x86_64",
    visibility = ["//visibility:public"],
)
