load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_platform//platform_data:defs.bzl", "platform_data")
load("//rust:defs.bzl", "rust_binary", "rust_library", "rust_test", "rustfmt_config")

_CARGO_TOML = "rust/Cargo.toml"

_DEPS = all_crate_deps(
    package_name = _CARGO_TOML,
    normal = True,
)

_PROC_MACRO_DEPS = all_crate_deps(
    package_name = _CARGO_TOML,
    proc_macro = True,
)

rustfmt_config(
    name = "enable-rustfmt",
)

platform_data(
    name = "selenium-manager-linux",
    platform = "//:linux_x86_64",
    tags = ["manual"],
    target = ":selenium-manager",
    visibility = ["//common/manager:__pkg__"],
)

platform_data(
    name = "selenium-manager-linux-arm64",
    platform = "//:linux_arm64",
    tags = ["manual"],
    target = ":selenium-manager",
    visibility = ["//common/manager:__pkg__"],
)

platform_data(
    name = "selenium-manager-macos",
    platform = "//:macos_arm64",
    tags = ["manual"],
    target = ":selenium-manager",
    visibility = ["//common/manager:__pkg__"],
)

platform_data(
    name = "selenium-manager-windows",
    platform = "//:windows_x86_64",
    tags = ["manual"],
    target = ":selenium-manager",
    visibility = ["//common/manager:__pkg__"],
)

platform_data(
    name = "selenium-manager-windows-arm64",
    platform = "//:windows_arm64",
    tags = ["manual"],
    target = ":selenium-manager",
    visibility = ["//common/manager:__pkg__"],
)

filegroup(
    name = "selenium-manager-dev",
    srcs = [
        ":selenium-manager-linux",
        ":selenium-manager-macos",
        ":selenium-manager-windows",
        ":selenium-manager-windows-arm64",
    ],
    tags = [
        "manual",
    ],
    visibility = [
        "//common/manager:__subpackages__",
    ],
)

rust_binary(
    # Yes, this name is very similar to the library. Note the dash
    # instead of an underscore
    name = "selenium-manager",
    srcs = ["src/main.rs"],
    edition = "2024",
    proc_macro_deps = _PROC_MACRO_DEPS,
    version = "0.4.41-nightly",
    visibility = ["//visibility:public"],
    deps = [
        ":selenium_manager",
    ] + _DEPS,
)

rust_library(
    # The name here is used as the crate name
    name = "selenium_manager",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["main.rs"],
    ),
    crate_features = select({
        "//common:stamp": [],
        "//conditions:default": ["avoid_stats"],
    }),
    edition = "2024",
    proc_macro_deps = _PROC_MACRO_DEPS,
    visibility = ["//rust:__subpackages__"],
    deps = _DEPS,
)

filegroup(
    name = "selenium_manager_srcs",
    srcs = [
        "Cargo.lock",
        "Cargo.toml",
        ":selenium_manager_rs_srcs",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "selenium_manager_rs_srcs",
    srcs = glob(["src/**/*.rs"]),
)

rust_test(
    name = "unit",
    size = "small",
    crate = ":selenium_manager",
    edition = "2024",
    tags = ["no-sandbox"],
)
