load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "storage",
    srcs = [
        "BrowsingContextPartitionDescriptor.java",
        "CookieFilter.java",
        "DeleteCookiesParameters.java",
        "GetCookiesParameters.java",
        "GetCookiesResult.java",
        "PartialCookie.java",
        "PartitionDescriptor.java",
        "PartitionKey.java",
        "SetCookieParameters.java",
        "StorageKeyPartitionDescriptor.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/bidi/network"],
    deps = [
        "//java/src/org/openqa/selenium/bidi/network",
        "//java/src/org/openqa/selenium/json",
    ],
)
