java_library(
  name = "log",
  srcs = glob(["*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium/io",
    "//java/client/src/org/openqa/selenium/remote",
    "//third_party/java/guava",
  ],
  visibility = [
    "//java/server/src/org/openqa/selenium/remote/server:__pkg__",
    "//java/server/src/org/openqa/grid:__pkg__",
    "//java/server/src/org/openqa/grid/selenium:__pkg__",
  ],
)
