load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "net",
    srcs = [
        "DefaultNetworkInterfaceProvider.java",
        "EphemeralPortRangeDetector.java",
        "FixedIANAPortRange.java",
        "HostIdentifier.java",
        "LinuxEphemeralPortRangeDetector.java",
        "NetworkInterface.java",
        "NetworkInterfaceProvider.java",
        "NetworkUtils.java",
        "OlderWindowsVersionEphemeralPortDetector.java",
        "PortProber.java",
        "UrlChecker.java",
        "Urls.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "@maven//:org_jspecify_jspecify",
    ],
)
