load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "support",
    srcs = [
        "AbstractFindByBuilder.java",
        "ByIdOrName.java",
        "CacheLookup.java",
        "Color.java",
        "Colors.java",
        "FindAll.java",
        "FindBy.java",
        "FindBys.java",
        "How.java",
        "PageFactory.java",
        "PageFactoryFinder.java",
        "ThreadGuard.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/support/pagefactory",
    ],
)
