load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "profiler",
    srcs = [
        "EventType.java",
        "HttpProfilerLogEntry.java",
        "ProfilerLogEntry.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//java/src/org/openqa/selenium/logging"],
)
