load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "web",
    srcs = [
        "CheckContentTypeHeader.java",
        "CheckOriginHeader.java",
        "ClassPathResource.java",
        "CombinedHandler.java",
        "EnsureSpecCompliantHeaders.java",
        "EnsureSpecCompliantResponseHeaders.java",
        "GridUiRoute.java",
        "HandlerNotFoundException.java",
        "JarFileResource.java",
        "MergedResource.java",
        "NoHandler.java",
        "PathResource.java",
        "Resource.java",
        "ResourceHandler.java",
        "ReverseProxyHandler.java",
        "RoutableHttpClientFactory.java",
        "StatusBasedReadinessCheck.java",
        "TeeReader.java",
        "Values.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = ["//java/src/org/openqa/selenium/remote/http"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/tracing",
        "@maven//:com_google_guava_guava",
    ],
)
