load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "config",
    srcs = [
        "SessionMapFlags.java",
        "SessionMapOptions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/sessionmap",
    ],
    deps = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/grid/sessionmap",
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
