load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "server",
    srcs = [
        "MessageInboundConverter.java",
        "MessageOutboundConverter.java",
        "NettyServer.java",
        "RequestConverter.java",
        "ResponseConverter.java",
        "SeleniumHandler.java",
        "SeleniumHttpInitializer.java",
        "ServerBindException.java",
        "WebSocketHandshakeComplete.java",
        "WebSocketMessageHandler.java",
        "WebSocketUpgradeHandler.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/tracing",
        "@maven//:com_google_guava_guava",
        "@maven//:io_netty_netty_buffer",
        "@maven//:io_netty_netty_codec_http",
        "@maven//:io_netty_netty_common",
        "@maven//:io_netty_netty_handler",
        "@maven//:io_netty_netty_transport",
    ],
)
