load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "download",
    srcs = ["driver.go"],
    importpath = "github.com/SeleniumHQ/selenium/golang/internal/download",
    visibility = ["//golang:__subpackages__"],
    deps = [
        "//golang/internal",
        "//golang/internal/platforms",
        "//golang/pkg/drivers",
        "@com_github_schollz_progressbar_v3//:progressbar",
        "@com_github_sirupsen_logrus//:logrus",
    ],
)
