load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "config",
    srcs = [
        "DistributorFlags.java",
        "DistributorOptions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/distributor",
        "//java/src/org/openqa/selenium/grid/distributor/selector",
    ],
    deps = [
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/distributor",
        "//java/src/org/openqa/selenium/grid/distributor/selector",
        "//java/src/org/openqa/selenium/grid/server",
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
