load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "config",
    srcs = [
        "AnnotatedConfig.java",
        "ClassCreation.java",
        "CompoundConfig.java",
        "ConcatenatingConfig.java",
        "Config.java",
        "ConfigException.java",
        "ConfigFlags.java",
        "ConfigValue.java",
        "Configs.java",
        "DescribedOption.java",
        "EnvConfig.java",
        "HasRoles.java",
        "JsonConfig.java",
        "MapConfig.java",
        "MemoizedConfig.java",
        "NonSplittingSplitter.java",
        "Role.java",
        "StandardGridRoles.java",
        "TomlConfig.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_guava_guava",
        "@maven//:org_tomlj_tomlj",
    ],
)
