load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "chromium",
    srcs = [
        "AddHasCasting.java",
        "AddHasCdp.java",
        "AddHasLaunchApp.java",
        "AddHasNetworkConditions.java",
        "AddHasPermissions.java",
        "ChromiumDriver.java",
        "ChromiumDriverCommandExecutor.java",
        "ChromiumDriverInfo.java",
        "ChromiumDriverLogLevel.java",
        "ChromiumNetworkConditions.java",
        "ChromiumOptions.java",
        "HasCasting.java",
        "HasCdp.java",
        "HasLaunchApp.java",
        "HasNetworkConditions.java",
        "HasPermissions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/devtools",
        "//java/src/org/openqa/selenium/html5",
        "//java/src/org/openqa/selenium/remote",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/bidi",
        "//java/src/org/openqa/selenium/devtools",
        "//java/src/org/openqa/selenium/devtools/noop",
        "//java/src/org/openqa/selenium/html5",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/logging",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/html5",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/service",
        "@maven//:com_google_auto_service_auto_service_annotations",
    ],
)
