load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")

filegroup(
    name = "web",
    srcs = glob([
        "*",
        "**/*",
    ]),
    visibility = [
        "//dotnet/test:__subpackages__",
        "//java/test/org/openqa/selenium/environment:__pkg__",
        "//py:__pkg__",
        "//rb/spec:__subpackages__",
    ],
)

copy_to_bin(
    name = "js-lib",
    srcs = [
        ":web",
    ],
    visibility = [
        "//javascript/node/selenium-webdriver:__subpackages__",
    ],
)
