java_library(
  name = "io",
  srcs = glob(["*.java"]),
  deps = [
    "//java/client/src/org/openqa/selenium",
  ],
  visibility = [
    "//java/client/src/org/openqa:__subpackages__",
    "//java/server/src/org/openqa:__subpackages__",
  ],
)