load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "security",
    srcs = [
        "AddSecretFilter.java",
        "BasicAuthenticationFilter.java",
        "RequiresSecretFilter.java",
        "Secret.java",
        "SecretOptions.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_google_guava_guava",
    ],
)
