load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "local",
    srcs = ["GuavaEventBus.java"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/internal",
        "@maven//:com_google_guava_guava",
    ],
)
