load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "docker",
    srcs = [
        "Container.java",
        "ContainerConfig.java",
        "ContainerId.java",
        "ContainerInfo.java",
        "ContainerLogs.java",
        "Device.java",
        "Docker.java",
        "DockerException.java",
        "DockerProtocol.java",
        "Image.java",
        "ImageId.java",
        "Port.java",
        "Version.java",
        "VersionCommand.java",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/docker/internal",
        "//java/src/org/openqa/selenium/docker/v1_41",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote/http",
        "@maven//:com_google_guava_guava",
    ],
)
