load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "local",
    srcs = ["LocalSessionMap.java"],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/sessionmap",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/grid/sessionmap",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/tracing",
    ],
)
