load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "local",
    srcs = [
        "LocalNode.java",
        "LocalNodeFactory.java",
        "SessionSlot.java",
    ],
    visibility = ["//:__subpackages__"],
    exports = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/node",
        "//java/src/org/openqa/selenium/io",
        "//java/src/org/openqa/selenium/remote/http",
    ],
    deps = [
        "//java/src/org/openqa/selenium",
        "//java/src/org/openqa/selenium/concurrent",
        "//java/src/org/openqa/selenium/events",
        "//java/src/org/openqa/selenium/grid/config",
        "//java/src/org/openqa/selenium/grid/data",
        "//java/src/org/openqa/selenium/grid/jmx",
        "//java/src/org/openqa/selenium/grid/log",
        "//java/src/org/openqa/selenium/grid/node",
        "//java/src/org/openqa/selenium/grid/node/config",
        "//java/src/org/openqa/selenium/grid/node/docker",
        "//java/src/org/openqa/selenium/grid/node/relay",
        "//java/src/org/openqa/selenium/grid/security",
        "//java/src/org/openqa/selenium/grid/server",
        "//java/src/org/openqa/selenium/internal",
        "//java/src/org/openqa/selenium/io",
        "//java/src/org/openqa/selenium/json",
        "//java/src/org/openqa/selenium/remote",
        "//java/src/org/openqa/selenium/remote/http",
        "//java/src/org/openqa/selenium/remote/service",
        "//java/src/org/openqa/selenium/remote/tracing",
        "@maven//:com_google_guava_guava",
    ],
)
